core:
  data_period:    3 # years
  max_threads:    20


analyzing:
  schemes:
    Baisc:
      desc: 'basic configuration'
      config:
        min_hist_data:  60 # days
        max_price:      30
        max_nmc:        200 # yi
        max_mktcap:     400 # yi
        max_pe:         .NaN
        exclude_gem:    false
        exclude_suspension: false
        exclude_st:     true
        min_turnover_avg: [[5, 5.0], [30, 2.0]]
        amp_scope:        [[90, 0.3, .NaN]]
        position:         [[60, 0.7], [420, 1.0]]
        min_change_count: [[90, 7, 3]]
        ma:               [[5, 10, 10]]
    Opportunity:
      desc: 'find opportunity policy'
      config:
        min_hist_data:  90 # days
        max_price:      40
        max_nmc:        200 # yi
        max_mktcap:     400 # yi
        exclude_gem:    false
        exclude_suspension: true
        exclude_st:         true
        raise_drop_scope:   [[30, -1.0, -0.50]]
        position:           [[60, 0.7], [420, 1.0]]


monitor:
  '002341':
    high:         20.0
    low:          19.0
    up_percent:   5.0
    down_percent: -5.0
  '300195':
    high:         19.0
    low:          18.0
    up_percent:   5.0
    down_percent: -5.0
